# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5382da6c5a2e0cdc901db2e7fbbb837b4b2ffd7ceb9d7cb565c188ac0665356b7edb5ef963a8fa4a49592204fda7785fac47f5b8f0d377dc17d923e1427fde8d

test:
  secret_key_base: 44b82f789f5a9f66974d150fcbf7767cdb3b5f611a6d587782a71eac9d6a22b39dfab814501c3e3df5bedec38b309cba52e1ed2f3fb07035df46bf6a9663e89c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
